### PR TITLE
Add option to skip photos

### PR DESCRIPTION
**Pull request by chisonne**
Users can use the --skip-photos option to donwload videos only.

### CODE REVIEW

**Comment by gilesknap** [comment]
Thanks for the PR. 

I'll merge this but please can you add a caveat to the main readme to say gphotos-sync cannot do a perfect backup, particularly of videos and reference #119.

I can do the wording if you prefer but not for a couple of weeks.

**Comment by chisonne** [comment]
Hi Giles,

Will update the PR in a week or 2.
Thanks for that information about the API issue. I was not aware of it.

Op zo 30 okt. 2022 08:42 schreef Giles Knap ***@***.***>:

**Comment by gilesknap** [comment]
I got around to updating the readme so will merge this.

I have to consolidate some of the container work and make another release sometime this month so your changes will release with that.

**Comment by gilesknap** [comment]
@chisonne I'm afraid you have broken some of the tests.

For details of how to run the tests locally and make a compliant contribution see https://github.com/gilesknap/gphotos-sync/blob/main/CONTRIBUTING.rst

Thanks,
giles.

**Comment by gilesknap** [comment]
I'm going to close this due to lack of response and because of #119 
Feel free to reopen if you still want to work on it.

**Pull request closed without merging**
