### PR TITLE
Apply max_filename to album links as well

### PR DESCRIPTION
**Pull request by lutzky**
Fixes gilesknap/gphotos-sync#285

### CODE REVIEW

**Comment by gilesknap** [comment]
Thanks this looks good. (We could add a regression test to demonstrate this working)

**Comment by lutzky** [comment]
I wanted to give that a try, but frankly I couldn't get the test suite running 😐

**Comment by gilesknap** [comment]
If you want to try.

pipenv install --dev
pipenv run pytest tests

you can use -k option of pytest to filter test names

**Comment by lutzky** [comment]
This turns out to require some refactoring; having a test in `test_system.py` send `args = ["--max-filename=..."]` does nothing; it needs to be plumbed separately in `test_setup()`'s call to `do_check`, and doing so is causing various other stuff to fail... Apologies, but this is too many face-homing rakes to step on for a weekend.

**Comment by gilesknap** [comment]
😎 I'll take a look next weekend, unless you want to have another go?

**Comment by lutzky** [comment]
It's all yours 😁

**Pull request merged**
