### PR TITLE
added ability to separate the folders for albums and shared albums

### PR DESCRIPTION
**Pull request by rui-nar**
added ability to separate the folders for albums and shared albums using command line arguments. It'll default to the albm folder if no shared album folder path is given.

### CODE REVIEW

**Comment by gilesknap** [comment]
We had a failure in the tests - but it was just a slightly timing sensitive test and re-run passed.

Note that the failure in the docker image build phase herer https://github.com/gilesknap/gphotos-sync/actions/runs/9368991609 is benign - its because the PR actions run with your permissions and can't see my docker credentials.

So all good. Merging.

Thanks!

**Comment by gilesknap** [comment]
@rui-nar let me know if you want me to release this or wait for more updates!

**Comment by rui-nar** [comment]
You can release it.
I have some other code tweaks but I'll open an "issue" first to explain my
approach since they change some aspects of the way of working. We'll see if
you like it or not. If you do I'll package and do a PR accordingly.

In any case, these were my first PRs and I'm really happy to contribute.
I'm building a more extensive workflow to work with Immich so maybe more
PRs will come, not sure yet.

**Comment by gilesknap** [comment]
Immich: that sounds interesting!

**Comment by gilesknap** [comment]
https://github.com/gilesknap/gphotos-sync/releases/tag/3.2.4

**Pull request merged**
