### PR TITLE
Add support for selecting multiple albums by regex

### PR DESCRIPTION
**Pull request by rogerdahl**

### CODE REVIEW

**Comment by gilesknap** [comment]
This looks good. It looks like the travis tests did not run though. I can't imagine why this is unless something has changed on github.

**Comment by gilesknap** [comment]
Oh wait, its just me. I won't see Travis runs from a fork. There does appear to be a failure in one system test however it is not related to your code changes. Rather it is seeing a bug in a new version of exif dependency see #250.

Many thanks for a really useful PR.

**Comment by rogerdahl** [comment]
Thanks for this project. The code is really well written and easy to work with :)

**Comment by gilesknap** [comment]
Hey thanks. Its been fun to write, but I must confess that my attention to this project is waning. Google's lack of attention to the issues in #119 is leading me to investigate alternative photos hosting projects. 

I'm not going to abandon gphotos-sync but would be interested in having some collaborators. Your PR showed a good understanding of the code, so I'm inviting you as collaborator. Feel free to refuse if this is not of interest!

**Comment by rogerdahl** [comment]
@gilesknap Thank you for the offer! Unfortunately, I have to decline due to time constrains, and because I don't want to make any promises that I can't keep. I still want to help though. Which of the current issues do you think would be a good one to start with?

**Comment by gilesknap** [comment]
No worries (note that accepting just means you have write permission to this repo - it does not come with any specific commitment!)

Thanks for the offer of looking at an issue.

Some possibilities are:
#244 should be quite easy and is stopping a couple of people from using gphotos-sync
#250 is an easy fix but would be worth discussing with the author of the exif library (who is very responsive)
#238 would be a little more involved but not that hard and useful for lots of people.

**Pull request merged**
