### PR TITLE
reduce log level for informative things from WARNING to INFO for less pollution of logs / cron

### PR DESCRIPTION
**Pull request by nohn**

### CODE REVIEW

**Comment by gilesknap** [comment]
Yep, not sure why I made this warnings in the first place.

**Comment by gilesknap** [comment]
@nohn I think we should make the default log level INFO. Otherwise many users will be surprised by lack of output.

**Comment by gilesknap** [comment]
@nohn OK now I remember why:

with log level INFO I get 
```
05-28 18:10:52 INFO     downloading 90 photos/2022/04/IMG_1839.HEIC 
05-28 18:10:52 INFO     downloading 91 photos/2022/04/IMG_1838.HEIC 
05-28 18:10:52 INFO     downloading 92 photos/2022/04/IMG_1837.HEIC 
05-28 18:10:52 INFO     downloading 93 photos/2022/04/IMG_1836.HEIC 
05-28 18:10:52 INFO     downloading 94 photos/2022/04/IMG_1835.HEIC 
05-28 18:10:53 INFO     downloading 95 photos/2022/04/IMG_1834.HEIC 
05-28 18:10:53 INFO     downloading 96 photos/2022/04/IMG_1833.HEIC 
05-28 18:10:54 INFO     downloading 97 photos/2022/04/IMG_1832.HEIC 
05-28 18:10:54 INFO     downloading 98 photos/2022/04/IMG_1831.HEIC 
05-28 18:10:55 INFO     downloading 99 photos/2022/04/IMG_1830.HEIC 
05-28 18:10:55 INFO     downloading 100 photos/2022/04/IMG_1829.HEIC 
05-28 18:10:55 INFO     downloading 101 photos/2022/04/IMG_1828.HEIC 
05-28 18:10:55 INFO     downloading 102 photos/2022/04/IMG_1827.HEIC 
```
etc.

So what I needed was an INFO and a VERBOSE INFO log level. You can add custom log levels to python logging. Maybe this is the way to go?

**Comment by gilesknap** [comment]
Just remembered that gphotos-sync already has the custom logging level TRACE so should be easy to:
- add one more custom level VERBOSE
- make the old INFO logs that you did not change into VERBOSE
- set the default to INFO
That way we get the same behaviour as before except that what was WARNING appears as INFO.
and using --log-level warning gets the quiet behaviour you wanted.

**Comment by nohn** [comment]
Well. There are current WARNINGS that I would like to see. Like photos NOT being downloaded.

**Comment by gilesknap** [comment]
> Well. There are current WARNINGS that I would like to see. Like photos NOT being downloaded.

Yes I'm suggesting that what you left as warning is still left as warning. But what was already INFO should be make into VERBOSE.

**Comment by nohn** [comment]
Is what I recently pushed what you are suggesting?

**Comment by gilesknap** [comment]
I'm afraid this does not run because you need to add the custom log level verbose in Logging.py e.g. trace is added here https://github.com/gilesknap/gphotos-sync/blob/main/src/gphotos_sync/Logging.py#L26-L28.

Also I think you changed all infos to verbose. That's not quite right, lets see if I can explain better. 

Take the original code before your PR and : 
- add a verbose custom logging level
- change all INFO logs to VERBOSE logs
- re-do your change: change many WARNINGS to INFO (but leave those that are actually WARNINGS)
- set the default log level to INFO

That's it. Do you think that is a sensible change that meets your requirement (for your requirement you would need to use --log-level WARNING -- for people that are happy with the way things were it will output the same information except that the 'WARNING' tags would change to 'INFO')

**Comment by gilesknap** [comment]
I've granted rights to run the CI so that you can see if the tests still work when you push changes to the PR.

**Pull request closed without merging**
