### PR TITLE
fixxing issues collected on #110

### PR DESCRIPTION
**Pull request by mprenditore**
All the different issues should be addressed now... more details on the different commit messages

### CODE REVIEW

**Comment by mprenditore** [comment]
I've never used Codecov so I don't know how to interpret the report.
Can you help me to understand it and what I did wrong to get this bad coverage?

Thanks

**Comment by gilesknap** [comment]
This is great work, thanks!

I've done some PEP8 tidy up and pushed those changes to feature2. Next, I will merge into master.

I use pycharm to keep the code nice and tidy with PEP8 rules, I have also just started using 'black' to format the code so merging this into master will be a little more effort than normal.

I also use the (paid feature) code coverage feature of pycharm which makes it easy to work out what code is not being tested and hence what codecov is complaining about. In this instance, it is very hard for us to write tests that will prove your changes since we need lots of filesystems, so we may need to accept a reduction of test coverage. I do run the test suite on Mac and Windows on Travis so we should be able to do some specific checks for the expected differences on those platforms.

One thing I'm not sure about is if your approach to checking for path and file length will work on Windows (probably will work on Mac?). Did you investigate that? gphotos-sync has quite a few Windows customers.

Cheers,
giles.

**Comment by mprenditore** [comment]
> I use pycharm to keep the code nice and tidy with PEP8 rules, I have also just started using 'black' to format the code so merging this into master will be a little more effort than normal.

Cool, I'll try to find time to study them, I mostly use python for automating more than normal developing.



> One thing I'm not sure about is if your approach to checking for path and file length will work on Windows (probably will work on Mac?). Did you investigate that? gphotos-sync has quite a few Windows customers.

I actually didn't, I don't have a Win machine so i couldn't test but from a quick research it will not work, but it should work on Mac because it's still Unix.
I'll try to find a way to implement a Win check for that.

Instead regarding the fix of the case insensitive, I misunderstood the problem so quite surely my fix will not solve the #133.
I'll try to find time to implement it iin the other way you've proposed:

- create a folder *TesT*
- put a file inside *T.temP*
- read the content of the folder
- if *T.tmpP* is not presen, it's insensitive

**Comment by gilesknap** [comment]
I've merged your changes into master now. If you would like to do any more, please take a branch from there.

Thanks for this, I'll continue the discussion on #110.

**Pull request merged**
